--------------------------------------------------------------------------------
-- Dependencies
--------------------------------------------------------------------------------

local m_camera = require("modules.camera")
local m_input = require("modules.input")
local m_ui = require("modules.ui")

local m_starly = require("starly.starly")

--------------------------------------------------------------------------------
-- Private Variables
--------------------------------------------------------------------------------

local _message_acquire_input_focus = hash("acquire_input_focus")

local _mouse_object = hash("/mouse")

--------------------------------------------------------------------------------
-- Private Functions
--------------------------------------------------------------------------------

local function handle_move()
	local mouse_position = m_input.get_mouse_position()
	local world_position = m_starly.screen_to_world(m_camera.object, mouse_position.x, mouse_position.y, true)
	if world_position then
		go.set_position(world_position, _mouse_object)
	end
end

--------------------------------------------------------------------------------
-- Public Functions
--------------------------------------------------------------------------------

function init(self)
	msg.post("#", _message_acquire_input_focus)
	m_ui.init(m_ui.group_editor)
end

function update(self, dt)
	m_ui.update()
	handle_move()
end